Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          translationLogger:
            default:
              class: Neos\Flow\Log\Backend\FileBackend
              options:
                logFileURL: '%FLOW_PATH_DATA%Logs/Translation.log'
                createParentDirectories: true
                severityThreshold: '%LOG_INFO%'
                maximumLogFileSize: 52428800
                logFilesToKeep: 5
                logMessageOrigin: false
